// extract.go — Parse and write extract blocks from cogdoc markdown files.
// ADR-040 Phase 1: build-time code extraction from .cog.md files.

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ExtractBlock represents a single extracted code block from a cogdoc.
type ExtractBlock struct {
	OutputPath string // Relative path for the output file
	Package    string // Optional package declaration to prepend
	Append     bool   // If true, append instead of overwrite
	Code       string // The extracted code (directives stripped)
	SourceFile string // The source .cog.md file
	LineNumber int    // Line number of the opening fence
}

// ParseExtractBlocks finds all fenced code blocks with // extract: directives
// and returns the parsed blocks.
func ParseExtractBlocks(content []byte, sourceFile string) ([]ExtractBlock, error) {
	var blocks []ExtractBlock
	lines := bytes.Split(content, []byte("\n"))

	i := 0
	for i < len(lines) {
		line := strings.TrimSpace(string(lines[i]))

		// Look for opening fence (triple backtick)
		if !strings.HasPrefix(line, "```") {
			i++
			continue
		}

		fenceLineNum := i + 1 // 1-indexed
		i++

		// Collect lines until closing fence
		var codeLines []string
		for i < len(lines) {
			cl := string(lines[i])
			if strings.TrimSpace(cl) == "```" {
				i++
				break
			}
			codeLines = append(codeLines, cl)
			i++
		}

		if len(codeLines) == 0 {
			continue
		}

		// Find first non-empty line
		firstNonEmpty := -1
		for j, cl := range codeLines {
			if strings.TrimSpace(cl) != "" {
				firstNonEmpty = j
				break
			}
		}
		if firstNonEmpty < 0 {
			continue
		}

		// Check for // extract: directive
		first := strings.TrimSpace(codeLines[firstNonEmpty])
		if !strings.HasPrefix(first, "// extract:") {
			continue
		}

		block := ExtractBlock{
			SourceFile: sourceFile,
			LineNumber: fenceLineNum,
		}

		// Parse directives — collect non-directive lines as code
		var codeBuf []string
		for _, cl := range codeLines {
			trimmed := strings.TrimSpace(cl)
			switch {
			case strings.HasPrefix(trimmed, "// extract:"):
				block.OutputPath = strings.TrimSpace(strings.TrimPrefix(trimmed, "// extract:"))
			case strings.HasPrefix(trimmed, "// package:"):
				block.Package = strings.TrimSpace(strings.TrimPrefix(trimmed, "// package:"))
			case strings.HasPrefix(trimmed, "// append:"):
				val := strings.TrimSpace(strings.TrimPrefix(trimmed, "// append:"))
				block.Append = val == "true"
			default:
				codeBuf = append(codeBuf, cl)
			}
		}

		if block.OutputPath == "" {
			continue
		}

		block.Code = strings.Join(codeBuf, "\n")
		// Trim leading/trailing blank lines from code
		block.Code = strings.TrimSpace(block.Code)

		blocks = append(blocks, block)
	}

	return blocks, nil
}

// WriteExtractBlocks writes each block to its output path relative to outDir.
// If dryRun is true, returns the paths without writing. Returns written file paths.
func WriteExtractBlocks(blocks []ExtractBlock, outDir string, dryRun bool) ([]string, error) {
	var written []string

	for _, b := range blocks {
		outPath := filepath.Join(outDir, b.OutputPath)
		written = append(written, outPath)

		if dryRun {
			continue
		}

		// Build output content
		var buf strings.Builder
		header := fmt.Sprintf("// Code generated by cog extract from %s; DO NOT EDIT.\n\n", b.SourceFile)
		if b.Append {
			// For append mode, don't add generation header on each append
		} else {
			buf.WriteString(header)
		}

		if b.Package != "" {
			buf.WriteString(fmt.Sprintf("package %s\n\n", b.Package))
		}

		buf.WriteString(b.Code)
		buf.WriteString("\n")

		// Ensure parent directory exists
		dir := filepath.Dir(outPath)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return written, fmt.Errorf("create directory %s: %w", dir, err)
		}

		if b.Append {
			f, err := os.OpenFile(outPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
			if err != nil {
				return written, fmt.Errorf("open %s for append: %w", outPath, err)
			}
			if _, err := f.WriteString(buf.String()); err != nil {
				f.Close()
				return written, fmt.Errorf("append to %s: %w", outPath, err)
			}
			f.Close()
		} else {
			if err := os.WriteFile(outPath, []byte(buf.String()), 0o644); err != nil {
				return written, fmt.Errorf("write %s: %w", outPath, err)
			}
		}
	}

	return written, nil
}
