package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseExtractBlocks_SingleBlock(t *testing.T) {
	content := []byte("# Doc\n\n```go\n// extract: cmd/main.go\nfmt.Println(\"hello\")\n```\n")

	blocks, err := ParseExtractBlocks(content, "doc.cog.md")
	if err != nil {
		t.Fatal(err)
	}
	if len(blocks) != 1 {
		t.Fatalf("expected 1 block, got %d", len(blocks))
	}

	b := blocks[0]
	if b.OutputPath != "cmd/main.go" {
		t.Errorf("OutputPath = %q, want %q", b.OutputPath, "cmd/main.go")
	}
	if b.Code != `fmt.Println("hello")` {
		t.Errorf("Code = %q, want %q", b.Code, `fmt.Println("hello")`)
	}
	if b.SourceFile != "doc.cog.md" {
		t.Errorf("SourceFile = %q, want %q", b.SourceFile, "doc.cog.md")
	}
	// The opening fence is on line 3 (1-indexed)
	if b.LineNumber != 3 {
		t.Errorf("LineNumber = %d, want %d", b.LineNumber, 3)
	}
}

func TestParseExtractBlocks_MultipleBlocks(t *testing.T) {
	content := []byte(strings.Join([]string{
		"# Doc",
		"",
		"```go",
		"// extract: a.go",
		"func A() {}",
		"```",
		"",
		"Some text",
		"",
		"```go",
		"// extract: b.go",
		"func B() {}",
		"```",
	}, "\n"))

	blocks, err := ParseExtractBlocks(content, "multi.cog.md")
	if err != nil {
		t.Fatal(err)
	}
	if len(blocks) != 2 {
		t.Fatalf("expected 2 blocks, got %d", len(blocks))
	}
	if blocks[0].OutputPath != "a.go" {
		t.Errorf("blocks[0].OutputPath = %q, want %q", blocks[0].OutputPath, "a.go")
	}
	if blocks[1].OutputPath != "b.go" {
		t.Errorf("blocks[1].OutputPath = %q, want %q", blocks[1].OutputPath, "b.go")
	}
	if blocks[0].Code != "func A() {}" {
		t.Errorf("blocks[0].Code = %q, want %q", blocks[0].Code, "func A() {}")
	}
	if blocks[1].Code != "func B() {}" {
		t.Errorf("blocks[1].Code = %q, want %q", blocks[1].Code, "func B() {}")
	}
}

func TestParseExtractBlocks_WithPackage(t *testing.T) {
	content := []byte("```go\n// extract: main.go\n// package: main\nfunc main() {}\n```\n")

	blocks, err := ParseExtractBlocks(content, "pkg.cog.md")
	if err != nil {
		t.Fatal(err)
	}
	if len(blocks) != 1 {
		t.Fatalf("expected 1 block, got %d", len(blocks))
	}
	if blocks[0].Package != "main" {
		t.Errorf("Package = %q, want %q", blocks[0].Package, "main")
	}
	// package directive should be stripped from Code
	if strings.Contains(blocks[0].Code, "// package:") {
		t.Errorf("Code should not contain package directive, got %q", blocks[0].Code)
	}
}

func TestParseExtractBlocks_WithAppend(t *testing.T) {
	content := []byte("```go\n// extract: out.go\n// append: true\nfunc Extra() {}\n```\n")

	blocks, err := ParseExtractBlocks(content, "app.cog.md")
	if err != nil {
		t.Fatal(err)
	}
	if len(blocks) != 1 {
		t.Fatalf("expected 1 block, got %d", len(blocks))
	}
	if !blocks[0].Append {
		t.Error("expected Append = true")
	}
}

func TestParseExtractBlocks_NoExtractDirective(t *testing.T) {
	content := []byte("```go\nfunc Foo() {}\n```\n")

	blocks, err := ParseExtractBlocks(content, "no-extract.cog.md")
	if err != nil {
		t.Fatal(err)
	}
	if len(blocks) != 0 {
		t.Fatalf("expected 0 blocks, got %d", len(blocks))
	}
}

func TestParseExtractBlocks_EmptyCodeBlock(t *testing.T) {
	content := []byte("```go\n```\n")

	blocks, err := ParseExtractBlocks(content, "empty.cog.md")
	if err != nil {
		t.Fatal(err)
	}
	if len(blocks) != 0 {
		t.Fatalf("expected 0 blocks for empty code block, got %d", len(blocks))
	}
}

func TestParseExtractBlocks_MixedBlocks(t *testing.T) {
	content := []byte(strings.Join([]string{
		"```go",
		"// extract: extracted.go",
		"func Yes() {}",
		"```",
		"",
		"```go",
		"func No() {}",
		"```",
		"",
		"```go",
		"// extract: also-extracted.go",
		"func AlsoYes() {}",
		"```",
	}, "\n"))

	blocks, err := ParseExtractBlocks(content, "mixed.cog.md")
	if err != nil {
		t.Fatal(err)
	}
	if len(blocks) != 2 {
		t.Fatalf("expected 2 blocks, got %d", len(blocks))
	}
	if blocks[0].OutputPath != "extracted.go" {
		t.Errorf("blocks[0].OutputPath = %q, want %q", blocks[0].OutputPath, "extracted.go")
	}
	if blocks[1].OutputPath != "also-extracted.go" {
		t.Errorf("blocks[1].OutputPath = %q, want %q", blocks[1].OutputPath, "also-extracted.go")
	}
}

func TestWriteExtractBlocks_Basic(t *testing.T) {
	dir := t.TempDir()
	blocks := []ExtractBlock{{
		OutputPath: "out.go",
		Code:       "func Hello() {}",
		SourceFile: "src.cog.md",
	}}

	paths, err := WriteExtractBlocks(blocks, dir, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(paths) != 1 {
		t.Fatalf("expected 1 path, got %d", len(paths))
	}

	data, err := os.ReadFile(filepath.Join(dir, "out.go"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)

	// Should contain generation header
	if !strings.Contains(content, "Code generated by cog extract from src.cog.md; DO NOT EDIT.") {
		t.Errorf("missing generation header in output:\n%s", content)
	}
	// Should contain the code
	if !strings.Contains(content, "func Hello() {}") {
		t.Errorf("missing code in output:\n%s", content)
	}
}

func TestWriteExtractBlocks_WithPackage(t *testing.T) {
	dir := t.TempDir()
	blocks := []ExtractBlock{{
		OutputPath: "out.go",
		Package:    "main",
		Code:       "func Hello() {}",
		SourceFile: "src.cog.md",
	}}

	_, err := WriteExtractBlocks(blocks, dir, false)
	if err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "out.go"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)

	if !strings.Contains(content, "package main") {
		t.Errorf("missing package declaration in output:\n%s", content)
	}
	// package declaration should come after the header and before the code
	headerIdx := strings.Index(content, "DO NOT EDIT.")
	pkgIdx := strings.Index(content, "package main")
	codeIdx := strings.Index(content, "func Hello() {}")
	if headerIdx >= pkgIdx || pkgIdx >= codeIdx {
		t.Errorf("unexpected ordering: header@%d, package@%d, code@%d", headerIdx, pkgIdx, codeIdx)
	}
}

func TestWriteExtractBlocks_DryRun(t *testing.T) {
	dir := t.TempDir()
	blocks := []ExtractBlock{{
		OutputPath: "should-not-exist.go",
		Code:       "func Nope() {}",
		SourceFile: "src.cog.md",
	}}

	paths, err := WriteExtractBlocks(blocks, dir, true)
	if err != nil {
		t.Fatal(err)
	}
	if len(paths) != 1 {
		t.Fatalf("expected 1 path returned, got %d", len(paths))
	}

	// File should NOT exist on disk
	outPath := filepath.Join(dir, "should-not-exist.go")
	if _, err := os.Stat(outPath); err == nil {
		t.Errorf("file %s should not exist in dry-run mode", outPath)
	}
}

func TestWriteExtractBlocks_Append(t *testing.T) {
	dir := t.TempDir()

	// First write (non-append) to create the file
	first := []ExtractBlock{{
		OutputPath: "combined.go",
		Code:       "func First() {}",
		SourceFile: "src.cog.md",
	}}
	_, err := WriteExtractBlocks(first, dir, false)
	if err != nil {
		t.Fatal(err)
	}

	// Second write (append) to add to the file
	second := []ExtractBlock{{
		OutputPath: "combined.go",
		Append:     true,
		Code:       "func Second() {}",
		SourceFile: "src.cog.md",
	}}
	_, err = WriteExtractBlocks(second, dir, false)
	if err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "combined.go"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)

	if !strings.Contains(content, "func First() {}") {
		t.Errorf("missing first function in output:\n%s", content)
	}
	if !strings.Contains(content, "func Second() {}") {
		t.Errorf("missing second function in output:\n%s", content)
	}
	// The append block should NOT add a second generation header
	count := strings.Count(content, "DO NOT EDIT.")
	if count != 1 {
		t.Errorf("expected exactly 1 generation header, found %d", count)
	}
}
